### ISSUE TITLE
Unable to render index.

### ISSUE THREAD

**Issue by geniusunil** [WarriorRocker/angular-xo-material#1]
After following the instructions at https://github.com/WarriorRocker/angular-xo-material under getting started and xampp on windows, my website shows nothing but an error "Unable to render index." What to do?

**Comment by WarriorRocker** [comment]
This is most likely that you need to compile the src app so there is a /dist folder with the index.html and other assets inside.

From the theme folder /wp-content/themes/angular-xo-material, run:

$ npm install
$ npm run build

Assuming you have node and the angular cli already installed.

I will only keep the source files in the repository. If I am eventually able to add the theme to the WordPress repository I would distribute the compiled theme after running: $ npm run deploy.

**Comment by geniusunil** [comment]
Thanks. The error is gone but i have a new problem in console 

"zone.js:3243 GET http://localhost/xo-api/routes/get 404 (Not Found)"
and my page is blank.

I guess I'll open a new issue for that

**Comment by WarriorRocker** [comment]
Thanks! I will respond to your other thread.
