### ISSUE TITLE
Http failure response for http://localhost:4200/xo-api/routes/get: 404 Not Found

### ISSUE THREAD

**Issue by Jaaaas** [WarriorRocker/angular-xo-material#11]
Hello, 
I have installed a fresh wordpress and added ACF and Xo for Angular plugin. I can successful see 
mydomain.it/xo-api/routes/get.

Later I downloaded and activated angular-xo-material. But when I run "npm run serve" there is this error in console:

![Schermata 2019-11-05 alle 15 55 35](https://user-images.githubusercontent.com/20561555/68218510-bf61e100-ffe4-11e9-9143-171478ed3d95.png)

**Comment by WarriorRocker** [comment]
Hi,

Check this page: https://angularxo.io/guides/angular-cli#add-appconfig-to-local-environment

Notice the apiUrl setting includes the full path.

You would then use `ng serve --configuration local`, or alias as an npm run command such as `npm run serve`.

https://angularxo.io/guides/angular-cli#npm-run-scripts

Alternatively you may also use a proxy config, I will most likely be updating Xo to use this approach in the near future.

https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/proxy.md

Let me know if that helps :)
