### ISSUE TITLE
zone.js:3243 GET http://localhost/xo-api/routes/get 404 (Not Found)

### ISSUE THREAD

**Issue by geniusunil** [WarriorRocker/angular-xo-material#2]
When i try to load the page with this theme, the page remains blank and i get this error in console :+1: 
"GET http://localhost/xo-api/routes/get 404 (Not Found)"

I don't have any directory called "xo-api". Did i miss a step?

**Comment by WarriorRocker** [comment]
Make sure the API is enabled in the settings from the WordPress admin.

Xo for Angular -> General Settings -> API:

API Enabled => true
API Endpoint => "/xo-api"

If this is correct can you try flushing the rewrites by visiting Settings -> Permalinks, and click "Save Changes".

I suggest using "/%postname%" for the "Custom Structure" on the permalink settings page.

Lastly make sure your .htaccess in the root of your wordpress installation has rewrites enabled: https://codex.wordpress.org/htaccess

Depending on your server setup you may need to enable mod_rewrite.

You should now be able to visit: http://localhost/xo-api/config/get

**Comment by geniusunil** [comment]
The error is gone, I don't know how.
