### ISSUE TITLE
Blank page.

### ISSUE THREAD

**Issue by geniusunil** [WarriorRocker/angular-xo-material#3]
The theme loads fine. I can se 'XO' in console. No errors. But it loads a blank page. Is that normal? I can change the angular code to display "hello world" or anything. But how does the theme work? How can i load content from my Wordpress site? How can i load "content" , "home" or "default" page?

**Comment by WarriorRocker** [comment]
Now you will need to create pages or update current pages to use one of the templates provided with the Xo Material theme. Once you update the template and add some content you should be able to preview or publish the page for view.

You can verify these routes by visiting (for your domain): https://angularxo.io/xo-api/routes/get

I also recommend creating a page which will serve as your 404 (page not found). First you create the page, select its template, add content and save. Next select this page in the Xo for Angular General Options -> Routing -> 404 Page screen and save.

This way all routes which are not valid will show this page instead, for instance: https://angularxo.io/notarealpage

**Comment by geniusunil** [comment]
Okay, i could see the sample page. From where does this  https://angularxo.io/xo-api/routes/get routes generate? How can i change them?

**Comment by WarriorRocker** [comment]
These are all generated automatically by the Xo for Angular plugin. They are based on all pages and posts which are public. If a template is not configured it will generally use the default template.

**Comment by geniusunil** [comment]
But it does not contain any path to my default public post "hello world!".

{"routes":[{"path":"xo-page-preview-3","loadChildren":".\/pages\/default\/default.module#XoMaterialDefaultPageModule","pathMatch":"full","data":{"postId":3}},{"path":"sample-page","loadChildren":".\/pages\/default\/default.module#XoMaterialDefaultPageModule","pathMatch":"full","data":false}],"success":true,"message":"Successfully retrieved routes."}

**Comment by WarriorRocker** [comment]
Can you please open a bug for this on the GitHub for the plugin itself?

https://github.com/WarriorRocker/angular-xo-core

If you are now able to see the theme I will close this particular issue.

Thanks!

**Comment by WarriorRocker** [comment]
I have added this issue here: https://github.com/WarriorRocker/angular-xo-core/issues/3
