### ISSUE TITLE
404 page not found in posts

### ISSUE THREAD

**Issue by med-amin** [WarriorRocker/angular-xo-material#5]
When I try to view the posts and the category I get 404 This page can't be found
![404](https://user-images.githubusercontent.com/46812464/55465338-d4ad0200-55f4-11e9-9865-e1befecebc89.png)

**Comment by med-amin** [comment]
I reinstall the plugin and the theme and now when I click on the page link in menu i get

`ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'sample-page'
Error: Cannot match any routes. URL Segment: 'sample-page'
    at ApplyRedirects.push../node_modules/@angular/router/fesm5/router.js.ApplyRedirects.noMatchError (router.js:2469)
    at CatchSubscriber.selector (router.js:2450)
    at CatchSubscriber.push../node_modules/rxjs/_esm5/internal/operators/catchError.js.CatchSubscriber.error (catchError.js:34)
    at MapSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._error (Subscriber.js:79)
    at MapSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.error (Subscriber.js:59)
    at MapSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._error (Subscriber.js:79)
    at MapSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.error (Subscriber.js:59)
    at MapSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._error (Subscriber.js:79)
    at MapSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.error (Subscriber.js:59)
    at TapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/tap.js.TapSubscriber._error (tap.js:61)
    at resolvePromise (zone.js:831)
    at resolvePromise (zone.js:788)
    at zone.js:892
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:17289)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at drainMicroTaskQueue (zone.js:601)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:502)
    at invokeTask (zone.js:1744)`

**Comment by WarriorRocker** [comment]
This may be related to https://github.com/WarriorRocker/angular-xo-core/issues/3

Can you copy here the routes generated that are being generated?

For instance: https://angularxo.io/xo-api/routes/get

**Comment by med-amin** [comment]
Okay 

`{
   "routes":[
      {
         "path":"xo-post-preview",
         "loadChildren":".\/pages\/posts\/posts.module#XoMaterialPostsPageModule",
         "pathMatch":"prefix",
         "data":{
            "postPreview":true
         }
      },
      {
         "path":"xo-blog-preview",
         "loadChildren":".\/pages\/posts\/posts.module#XoMaterialPostsPageModule",
         "pathMatch":"prefix",
         "data":{
            "postPreview":true
         }
      },
      {
         "path":"blog\/",
         "loadChildren":".\/pages\/content\/content.module#XoMaterialContentPageModule",
         "pathMatch":"full",
         "data":false
      },
      {
         "path":"",
         "loadChildren":".\/pages\/home\/home.module#XoMaterialHomePageModule",
         "pathMatch":"full",
         "data":false
      },
      {
         "path":"privacy-policy\/",
         "loadChildren":".\/pages\/content\/content.module#XoMaterialContentPageModule",
         "pathMatch":"full",
         "data":false
      },
      {
         "path":"sample-page\/",
         "loadChildren":".\/pages\/default\/default.module#XoMaterialDefaultPageModule",
         "pathMatch":"full",
         "data":false
      },
      {
         "path":"hello-world\/",
         "loadChildren":".\/pages\/posts\/posts.module#XoMaterialPostsPageModule",
         "pathMatch":"full",
         "data":false
      },
      {
         "path":"blog",
         "loadChildren":".\/pages\/posts\/posts.module#XoMaterialPostsPageModule",
         "pathMatch":"prefix",
         "data":{
            "postType":"blog"
         }
      },
      {
         "path":"**",
         "loadChildren":".\/pages\/default\/default.module#XoMaterialDefaultPageModule",
         "pathMatch":"full",
         "data":{
            "url":"\/404-2\/"
         }
      }
   ],
   "success":true,
   "message":"Successfully retrieved routes."
}`

**Comment by WarriorRocker** [comment]
Can you update your permalink settings like this: https://angularxo.io/guides/wordpress#permalink-settings

It looks like the trailing slash in the route path is throwing off Angular's router. I plan to fix this within Xo by trimming the trailing slash on the path pattern, for now you should be able to overcome this issue by updating your permalink settings based off the guide above.

**Comment by med-amin** [comment]
Thanks now the pages are working but the posts still

**Comment by WarriorRocker** [comment]
Looking at your routes, the posts template is only compatible with a post type which has a rewrite base (/blog for instance). This template also expects the following route pattern for category and post slugs:

/blog/:category
/blog/:category/:slug

There is an example of this in the theme at https://github.com/WarriorRocker/angular-xo-material/blob/master/inc/blog.inc.php

Otherwise for a post type without a rewrite base, such as "post" by default, will need to use one of the standalone templates like default or content.

![image](https://user-images.githubusercontent.com/2924540/55477913-4e8abe80-55e8-11e9-875b-227da138eb1a.png)

**Comment by med-amin** [comment]
@WarriorRocker  Thanks now the posts are working

**Comment by WarriorRocker** [comment]
The categories will only work when using the posts template, requiring your posts to have a rewrite base such as "/blog".

Explanation:
For posts with a rewrite base it is possible to generate a single route which points to the posts template module. This module has parameterized routes for categories and posts that fall within that rewrite base.

The posts module also defines a module/component which will render the category page.

Post types which do not have a rewrite base (post by default) all routes have to be generated individually. Because if we placed a path as ":slug" or ":category" at the root of the generated routes it would match all URLs and cause normal pages to not display.

Xo does not currently have a way to specify a template used for a category page other than using the posts template.

**Comment by med-amin** [comment]
@WarriorRocker  No even on categories with slug base on :blog  the redirect to the home page

**Comment by WarriorRocker** [comment]
First can you go to the Permalink Settings page and hit save? Just want to eliminate that as a possible issue. Also if you're using Chrome I recommend trying to view the URL with the dev tools window open and the Disable cache option checked on the Network tab.

If it is still not working can you give me an example post and category URL you are trying to navigate? And an updated output of your routes as well.

When you edit a category or post in WordPress can you make sure that the view URL looks correct as well?

**Comment by med-amin** [comment]
I tried to save the permalinks and i tried to disable the cache from chrome network tab but the problem persist also i find a javascript error in the console 

`ERROR Error: Uncaught (in promise): [object Undefined]
    at resolvePromise (zone.js:831)
    at resolvePromise (zone.js:788)
    at zone.js:892
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:17289)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at drainMicroTaskQueue (zone.js:601)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:502)
    at invokeTask (zone.js:1744)`

 the blog post /blog/category/testing
the category /blog/gdfgdfgdfg
the routes 
`{"routes":[{"path":"xo-post-preview","loadChildren":".\/pages\/default\/default.module#XoMaterialDefaultPageModule","pathMatch":"prefix","data":{"postPreview":true}},{"path":"xo-blog-preview","loadChildren":".\/pages\/posts\/posts.module#XoMaterialPostsPageModule","pathMatch":"prefix","data":{"postPreview":true}},{"path":"blog","loadChildren":".\/pages\/content\/content.module#XoMaterialContentPageModule","pathMatch":"full","data":false},{"path":"","loadChildren":".\/pages\/home\/home.module#XoMaterialHomePageModule","pathMatch":"full","data":false},{"path":"privacy-policy","loadChildren":".\/pages\/content\/content.module#XoMaterialContentPageModule","pathMatch":"full","data":false},{"path":"sample-page","loadChildren":".\/pages\/default\/default.module#XoMaterialDefaultPageModule","pathMatch":"full","data":false},{"path":"hello-world","loadChildren":".\/pages\/default\/default.module#XoMaterialDefaultPageModule","pathMatch":"full","data":false},{"path":"blog","loadChildren":".\/pages\/posts\/posts.module#XoMaterialPostsPageModule","pathMatch":"prefix","data":{"postType":"blog"}},{"path":"**","loadChildren":".\/pages\/default\/default.module#XoMaterialDefaultPageModule","pathMatch":"full","data":{"url":"\/404-2"}}],"success":true,"message":"Successfully retrieved routes."}`

**Comment by WarriorRocker** [comment]
If your category has the slug "gdfgdfgdfg" your full blog post URL should look something like: /blog/gdfgdfgdfg/testing

Note that you need to add a category to the blog post "testing", in this case "gdfgdfgdfg". If the URL still has "category" it means there was no category assigned to that blog post. While the post URL should work, the category URL will only work when there is at least one post using that category. This is based off the default WordPress behavior to hide empty categories.

**Comment by med-amin** [comment]
@WarriorRocker  Thanks it was the empty category  so the post must be assigned to a category to be seen
and the category itself can't be seen if she has no posts

**Comment by WarriorRocker** [comment]
Glad to hear it is working. Closing this issue.

Thanks for your patience!
