### ISSUE TITLE
How can i connect to my created api controller from a component

### ISSUE THREAD

**Issue by med-amin** [WarriorRocker/angular-xo-material#6]
I already created a controller and the API works fine but I can't get information from the API into my component and i already created an options service that extends the XoApiService class

**Comment by WarriorRocker** [comment]
Are you able to view the new API directly in your browser? For instance: https://angularxo.io/xo-api/config/get

Could you please post additional details such as an example URL where your endpoint is found, and the service created to consume.

Do you see the request in your network inspector within hte browser dev tools?

Here is a full process for how the Xo Material theme loads the main navigation items:

1. [Register Menus Controller](https://github.com/WarriorRocker/angular-xo-core/blob/master/Includes/Api/Controllers/MenusController.class.php)
2. [Register Menus Service](https://github.com/WarriorRocker/angular-xo-node/blob/master/lib/src/services/api/menus/menus.service.ts)
3. [Consume Menus Service](https://github.com/WarriorRocker/angular-xo-material/blob/master/src/app/components/header/header.component.ts)
4. [Display Menu Items](https://github.com/WarriorRocker/angular-xo-material/blob/master/src/app/components/header/header.component.html)

**Comment by med-amin** [comment]
@WarriorRocker Thanks for your reply but when I was trying to reinstall the package again I end up with a new error  in the API
`core.js:15735 ERROR HttpErrorResponseerror: {error: SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at XMLHtt…, text: "<!doctype html>
↵<html lang="en">
↵<head>
↵    <ba…aterial/dist/main.js"></script></body>
↵</html>
↵"}headers: HttpHeaders {normalizedNames: Map(0), lazyUpdate: null, lazyInit: ƒ}message: "Http failure during parsing for http://wordpress-angular.me/"name: "HttpErrorResponse"ok: falsestatus: 200statusText: "OK"url: "http://wordpress-angular.me/"__proto__: HttpResponseBase
defaultErrorLogger @ core.js:15735`

**Comment by WarriorRocker** [comment]
You may need to [update the Permalink Settings like this](https://angularxo.io/guides/wordpress#permalink-settings), even if it is already set this way save the settings on this page to have WordPress rebuild its internal rewrites.

Next make sure you can see one of the API endpoints directly in your browser such as: https://angularxo.io/xo-api/config/get

Replacing "https://angularxo.io" with your host.

**Comment by med-amin** [comment]
@WarriorRocker I tried to update the permalink setting as in the picture and i can access the API config
`{"config":{"app":{"title":"Wordpress angular","url":"http:\/\/wordpress-angular.me","version":"0.1.4","debug":false},"paths":{"apiUrl":"\/xo-api\/","templateUrl":"\/wp-content\/themes\/angular-xo-material\/"}},"success":true,"message":"Successfully generated config."}
`

**Comment by WarriorRocker** [comment]
Can you provide excerpts or samples of your code based on the following so that I can troubleshoot this further? 

1. The [controller class](https://github.com/WarriorRocker/angular-xo-core/blob/master/Includes/Api/Controllers/MenusController.class.php)
2. Registering the controller [like this](https://github.com/WarriorRocker/angular-xo-core/blob/master/Includes/Api/Api.class.php#L38) or [like this](https://angularxo.io/api/controllers#adding-a-new-api-controller)
3. [Register API service](https://github.com/WarriorRocker/angular-xo-node/blob/master/lib/src/services/api/menus/menus.service.ts)
4. [Consume API service](https://github.com/WarriorRocker/angular-xo-material/blob/master/src/app/components/header/header.component.ts#L21)

**Comment by med-amin** [comment]
@WarriorRocker I removed the controller class and I tried as a fresh install without any additional coding, also  I created a [Repository](https://github.com/med-amin/angular-xo)  with the installation that I have and you can find the   [SQL file](https://github.com/med-amin/angular-xo/blob/master/angular-xo.sql)

**Comment by med-amin** [comment]
@WarriorRocker No, solution?
