### ISSUE TITLE
Some of the theme features are not available out of the box

### ISSUE THREAD

**Issue by gsse7en** [WarriorRocker/angular-xo-material#7]
I am really fond of this plugin, but there are issues I can't figure out with guides and Api documentation:
1. I have a GET request from main page that knocks to "/xo-api//routes/get" endpoint, but I can't find where it comes from. From the api the only place where this service is used is in the "angular-xo-material/src/app/components/sitemap/sitemap.component.ts", but it never fires. So to fix the double slash in "xo-for-angular" wp plugin folder, I have to go to "wp/wp-content/plugins/xo-for-angular/Includes/Api/Controllers/ConfigController.class.php"(:29) `'apiUrl' => $this->Xo->Services->Options->GetOption('xo_api_endpoint') . '/',`
and remove the trailing slash.
2. Routes don't work. In Angular routes(app.routing.module), the names of the routes are like this: `path: 'xo-material-page-default'`. Should I change them or they are intended to be named like this?
3. When I fix the GET '"/xo-api/routes/get' endpoint - I receive the array of routes, but they don't work. Should I put them as angular routes somehow?
4. In the "xo-for-angular" wp plugin folder - the route names are like this: `'xo-page-preview-' . $postId`, that doesn't work. Should I change names and should I implement routes in Angular manually?
5. in api docs, when fetching Posts with XoApiPostService there is no getPage method
6. How to show wp pages content that are made with builder? Their content looks like this: `[vc_row]...[/vc_row]` but never shows as html.

**Comment by gsse7en** [comment]
7. In the theme there is a header and footer. Header shows the list of Left and Right nav menus, but the footer is absent. The network tab shows that I get the response for footer with an error message: "No allowed groups are defined."

**Comment by WarriorRocker** [comment]
Hi, thanks for the great feedback!

Based on some of your points above it seems that you may be missing the angular-xo module in your Angular app or it is not fully configured.

The [routes defined in the app.routing.ts](https://github.com/WarriorRocker/angular-xo-material/blob/master/src/app/app.routing.ts) are there only so the Angular CLI compiles and includes these modules in the dist folder when building or deploying the theme. The modules are lazy-loaded but unless defined with some sort of route won't be available when the real routes load.

When fully enabled the angular-xo module will replace these routes with those generated dynamically by the Xo for Angular API.

Check [this example of an app.module.ts](https://github.com/WarriorRocker/angular-xo-material/blob/master/src/app/app.module.ts) which includes the provider and initialization of the  XoRouteService.

If you wish to statically define your routes then replace them in the app.routing.ts file and do not include the provider for the XoRouteService.

That should address your items 1-4.

5. Thank you for pointing this out, the [XoApiPostService](https://github.com/WarriorRocker/angular-xo-node/blob/master/lib/src/services/api/posts/posts.service.ts) indeed no longer has the "getPage" method, this was named to simply "get" for consistency with the other services. I have updated the [Posts API docs](https://angularxo.io/api/controllers/posts) accordingly.

6. The [Xo Material](https://github.com/WarriorRocker/angular-xo-material) theme relies heavily on [ACF Pro](https://www.advancedcustomfields.com/pro/) for page templates like home, content, post, and sitemap. The default template uses the default WordPress editor, either the legacy wysiwyg or newer Gutenberg editor. I have been able to test with both and see the output in the default template.

7. This may be related to 6, without ACF Pro the footer options (or theme options in general) won't show. Xo for Angular gives options to set which ACF Option groups should be allowed over the API.

**Comment by gsse7en** [comment]
Thank you very much for your answer! In my case though the problem was in Permalinks Settings. 
I had "/%postname%/", should be "/%postname%"

**Comment by WarriorRocker** [comment]
Glad you got it working!
