### ISSUE TITLE
XoResolver Error Handling and Routing  - Unable to locate term or post

### ISSUE THREAD

**Issue by atschak** [WarriorRocker/angular-xo-material#9]
I'm using the xo-api in a custom theme.
 
Everything works fine, when I call existing taxonomies or cpt's.

e.g. /taxomomy/term/post **or**
     /taxomomy/term

In this case:

 /taxomomy/term/post-not-existing **or**
 /taxomomy/term-not-existing

an js error occurs

```
main.c8b206c087083dd18b04.js:1 ERROR Error: Uncaught (in promise): [object Undefined]
    at R (polyfills.740947e94c0b9ca6fd5d.js:1)
    at R (polyfills.740947e94c0b9ca6fd5d.js:1)
    at polyfills.740947e94c0b9ca6fd5d.js:1
    at e.invokeTask (polyfills.740947e94c0b9ca6fd5d.js:1)
    at Object.onInvokeTask (main.c8b206c087083dd18b04.js:1)
    at e.invokeTask (polyfills.740947e94c0b9ca6fd5d.js:1)
    at t.runTask (polyfills.740947e94c0b9ca6fd5d.js:1)
    at g (polyfills.740947e94c0b9ca6fd5d.js:1)
    at t.invokeTask [as invoke] (polyfills.740947e94c0b9ca6fd5d.js:1)
    at _ (polyfills.740947e94c0b9ca6fd5d.js:1)
```
The request response of xo-api is correct:
```
{term: null, success: false, message: "Unable to locate term."}
message: "Unable to locate term."
success: false
term: null
```
```
{post: null, success: false, message: "Unable to locate post."}
message: "Unable to locate post."
post: null
success: false
```
I would expect to be redirected to the 404 page, but a blank page is displayed. 
Is there a way to fix this js error and automatically redirect to the 404 page?

404 redirect for missing pages works perfectly.

Angular _router.events.NavigationError returns:
`t {id: 1, url: "/taxonomy/term-not-existing", error: undefined}`

**WP-Setup:**
ACF Pro
CPT e.g. portfolio
Custom Taxonomy e.g portfolio_category

**Comment by atschak** [comment]
Hi, 
no suggestions or ideas?

**Comment by WarriorRocker** [comment]
Hi,

Apologies for the late reply, just got back from vacation.

This is an area I would like to conduct additional research. When the resolver is rejected there doesn't seem to be a way to handle that rejection outside of the resolver itself.

The question then, as to how we handle that rejection I believe can be somewhat opinionated. In the case of this theme it makes sense to send the user to our 404 page. However there are other cases such as showing a modal or triggering a logging action that I wanted to be up to the application developer.

https://github.com/angular/angular/issues/12343#issuecomment-255876103

Based on the linked comment, as the navigation event is likely invoked by clicking on a RouterLink, the only solution is to subscribe for NavigationError events from the Router.

I went ahead and added a temporary solution for this to the Xo Material theme.

https://github.com/WarriorRocker/angular-xo-material/blob/master/src/app/app.component.ts#L24

The error does still show in the console and the URL appears to go to the root and back to the URL which produced the error then showing the 404 page, not sure if these are really a problems or just minor annoyances.

Additionally looking into a way to potentially specify a default "send to 404" setting for the angular-xo module as this will probably be the majority use case. Also it may be possible to return the Observable of the API call instead, though this may defeat the purpose of using the resolver in the first place.

Certainly open to a better solution or any thoughts. Thanks!
